version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: web-service-db
      POSTGRES_USER: web-service
      POSTGRES_PASSWORD: db-password
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432